version: '3.7'
services:
   
   horizontal-backend:
      build:
            context: ./horizontal-back
            dockerfile: Dockerfile
      ports:
            - "8080:8080"
      restart: always
      volumes:
            - ../datos/horizontal/:/home/horizontal
      environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql_host:3306/promocionhorizontal?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: c3c1t3.2021
      networks:
            - mysql_network
      logging:
            options:
               max-size: "10m"
               max-file: "3"

networks:
   mysql_network:
      name: mysql_network
      external: true
